name: Build and Release WindC

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v'
  workflow_dispatch: # Allow manual triggering from the GitHub Actions UI
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Install dependencies
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    # Set the VERSION file if manual trigger
    - name: Set Version File from Manual Trigger
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version }}
      run: echo "${{ github.event.inputs.version }}" > VERSION

    # Set the VERSION file from Git tag if it's a push trigger
    - name: Set Version from Tag
      if: ${{ github.event_name == 'push' }}
      run: echo "${{ github.ref_name }}" > VERSION

    # Run the build script
    - name: Build and Package WindC
      run: |
        chmod +x utils/distribute.sh
        ./utils/distribute.sh

    # Upload the tarball as an artifact
    - name: Upload Distribution Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windc-dist-${{ github.event.inputs.version || github.ref_name }}
        path: windc-dist-${{ github.event.inputs.version || github.ref_name }}/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Checkout the code (required for GitHub Actions context)
    - name: Checkout Code
      uses: actions/checkout@v4

    # Upload the tarball to GitHub Release
    - name: Upload Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: windc-dist-*
        tag: ${{ github.ref_name }}
